<?php

namespace ContainerRYFjxI0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DaVKAZHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.daVKAZH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.daVKAZH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'sectionRepository' => ['privates', 'App\\Repository\\SectionRepository', 'getSectionRepositoryService', true],
            'sectionTypeWebsitePageRepository' => ['privates', 'App\\Repository\\SectionTypeWebsitePageRepository', 'getSectionTypeWebsitePageRepositoryService', true],
        ], [
            'entityManagerInterface' => '?',
            'sectionRepository' => 'App\\Repository\\SectionRepository',
            'sectionTypeWebsitePageRepository' => 'App\\Repository\\SectionTypeWebsitePageRepository',
        ]);
    }
}
