<?php

namespace ContainerRYFjxI0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WnOat3uService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wnOat3u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wnOat3u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'clientSectionRepository' => ['privates', 'App\\Repository\\ClientSectionRepository', 'getClientSectionRepositoryService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'clientSectionRepository' => 'App\\Repository\\ClientSectionRepository',
            'serializer' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
