<?php

namespace ContainerRYFjxI0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PGHiVSeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pGHiVSe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pGHiVSe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryProductRepository' => ['privates', 'App\\Repository\\CategoryProductRepository', 'getCategoryProductRepositoryService', true],
            'clientRepository' => ['privates', 'App\\Repository\\ClientRepository', 'getClientRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'productCategoryValueRepository' => ['privates', 'App\\Repository\\ProductCategoryValueRepository', 'getProductCategoryValueRepositoryService', true],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'productVariationValueRepository' => ['privates', 'App\\Repository\\ProductVariationValueRepository', 'getProductVariationValueRepositoryService', true],
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'sousCategoryProductRepository' => ['privates', 'App\\Repository\\SousCategoryProductRepository', 'getSousCategoryProductRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'variationProductRepository' => ['privates', 'App\\Repository\\VariationProductRepository', 'getVariationProductRepositoryService', true],
        ], [
            'categoryProductRepository' => 'App\\Repository\\CategoryProductRepository',
            'clientRepository' => 'App\\Repository\\ClientRepository',
            'entityManagerInterface' => '?',
            'productCategoryValueRepository' => 'App\\Repository\\ProductCategoryValueRepository',
            'productRepository' => 'App\\Repository\\ProductRepository',
            'productVariationValueRepository' => 'App\\Repository\\ProductVariationValueRepository',
            'serializer' => '?',
            'sousCategoryProductRepository' => 'App\\Repository\\SousCategoryProductRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
            'variationProductRepository' => 'App\\Repository\\VariationProductRepository',
        ]);
    }
}
