<?php

namespace ContainerRYFjxI0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSiteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SiteController' shared autowired service.
     *
     * @return \App\Controller\SiteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'SiteController.php';

        $container->services['App\\Controller\\SiteController'] = $instance = new \App\Controller\SiteController(($container->privates['App\\Service\\DomainService'] ?? $container->load('getDomainServiceService')), ($container->privates['App\\Repository\\ClientRepository'] ?? $container->load('getClientRepositoryService')), ($container->privates['App\\Repository\\SectionRepository'] ?? $container->load('getSectionRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\SiteController', $container));

        return $instance;
    }
}
