<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRYFjxI0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRYFjxI0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRYFjxI0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRYFjxI0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRYFjxI0\App_KernelDevDebugContainer([
    'container.build_hash' => 'RYFjxI0',
    'container.build_id' => 'a4fccb81',
    'container.build_time' => 1727192889,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRYFjxI0');
